# Generated by Django 5.2.4 on 2025-07-15 16:14

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.common.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(db_index=True, max_length=255)),
            ],
            options={
                "indexes": [models.Index(fields=["label"], name="account_wal_label_160427_idx")],
            },
            bases=(apps.common.mixins.SafeSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("txid", models.CharField(db_index=True, max_length=255, unique=True)),
                ("amount", models.DecimalField(decimal_places=18, max_digits=36)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="account.wallet",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["txid"], name="account_tra_txid_716d90_idx"),
                    models.Index(
                        fields=["wallet", "amount"], name="account_tra_wallet__b3ed30_idx"
                    ),
                ],
            },
            bases=(apps.common.mixins.SafeSaveMixin, models.Model),
        ),
    ]
